[font]
normal = { family = "FiraCode Nerd Font" }
size = 12.25 

[cursor]
style = { shape = "Beam", blinking = "On" }

[window]
padding = { x = 16, y = 16 }
dynamic_padding = false

[colors]
footer_bar = { foreground = "#ffffff", background = "#262626" }


[colors.primary]
foreground = "#ffffff"
background = "#161616"

[colors.search]
matches = { foreground = "CellBackground", background = "#ee5396" }

[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"
